# azure-pipelines.yml
trigger:
- main

pool:
  name: magedpool

variables:
  imageName: 'foodcart-node'
  acrName: 'myzomato'          # your ACR name
  dockerfilePath: '.github/manifests/Dockerfile'
  imageTag: '$(Build.BuildId)' # unique per build

steps:
# 1️⃣ Install Node.js and dependencies
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Use Node.js 20'

- script: |
    npm install
    npm test || echo "no tests"
  displayName: 'Install & Test'

# 2️⃣ Build and push Docker image to ACR using Azure CLI
- task: AzureCLI@2
  displayName: 'Build & Push Docker image using ACR'
  inputs:
    azureSubscription: 'ACR-myzomato'  # your service connection
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      echo "Building Docker image and pushing to ACR..."
      az acr build \
        --registry $(acrName) \
        --image $(imageName):$(imageTag) \
        --file $(dockerfilePath) \
        .
