trigger:
- main

variables:
  dockerRegistryServiceConnection: '467aebc6-c2d7-48d1-af79-d79a67c80398'
  imageRepository: 'foodcart-node'
  containerRegistry: 'myacr.azurecr.io'
  dockerfilePath: '.github/manifests/Dockerfile'
  tag: '$(Build.BuildId)'

  azureSubscriptionEndpoint: 'default'
  azureResourceGroup: 'Nayana'
  kubernetesCluster: 'managedevopsagent'
  namespace: 'prod'
  manifestsPath: '.github/manifests/deployment.yaml'

pool:
  name: magedpool

stages:
# ========== BUILD STAGE ==========
- stage: Build
  displayName: 'Build and Push Docker Image'
  jobs:
  - job: Build
    displayName: 'Build & Push Image'
    steps:
    - checkout: self

    - script: |
        echo "Listing repository files..."
        ls -R
      displayName: 'List Files in Repo'

    # ✅ Install Docker manually
    - script: |
        echo "Installing Docker..."
        sudo apt-get update -y
        sudo apt-get install -y ca-certificates curl gnupg lsb-release apt-transport-https software-properties-common
        sudo mkdir -p /etc/apt/keyrings
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
        echo \
          "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
          https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | \
          sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
        sudo apt-get update -y
        sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
        sudo usermod -aG docker $(whoami)
        sudo systemctl start docker
        sudo systemctl enable docker
        sudo docker version
      displayName: 'Install Docker on Managed Agent'

    # ✅ Install Azure CLI
    - script: |
        echo "Installing Azure CLI..."
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
        az version
      displayName: 'Install Azure CLI'

    # ✅ Login to Azure & ACR
    - script: |
        echo "Logging into Azure..."
        az login --identity || echo "Using Managed Identity if available"
        echo "Logging into ACR..."
        az acr login --name myacr
      displayName: 'Login to Azure and ACR'

    # ✅ Build Docker image
    - script: |
        echo "Building Docker image..."
        sudo docker build -t $(containerRegistry)/$(imageRepository):$(tag) -f $(dockerfilePath) .
      displayName: 'Build Docker Image'

    # ✅ Push Docker image
    - script: |
        echo "Pushing image to ACR..."
        sudo docker push $(containerRegistry)/$(imageRepository):$(tag)
      displayName: 'Push Docker Image to ACR'

    # ✅ Update manifest with new tag
    - script: |
        echo "Updating manifest with image tag..."
        sed -i "s|image: .*|image: $(containerRegistry)/$(imageRepository):$(tag)|" $(manifestsPath)
      displayName: 'Update Kubernetes Manifest'

    - publish: .github/manifests
      artifact: manifests

# ========== DEPLOY STAGE ==========
- stage: Deploy
  displayName: 'Deploy to AKS'
  dependsOn: Build
  jobs:
  - job: Deploy
    displayName: 'Deploy Application to AKS'
    steps:
    - download: current
      artifact: manifests

    - task: Kubernetes@1
      displayName: 'Deploy to AKS'
      inputs:
        connectionType: 'Azure Resource Manager'
        azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
        azureResourceGroup: $(azureResourceGroup)
        kubernetesCluster: $(kubernetesCluster)
        namespace: $(namespace)
        command: 'apply'
        useConfigurationFile: true
        configuration: '$(Pipeline.Workspace)/manifests/deployment.yaml'
