# azure-pipelines.yml
trigger:
- main

pool:
  name: magedpool

variables:
  imageName: 'foodcart-node'

steps:
# 1️⃣ Install dependencies and test
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Use Node.js 20'

- script: |
    npm install
    npm test || echo "no tests"
  displayName: 'Install & Test'

# 2️⃣ Build and push Docker image
- task: AzureCLI@2
  displayName: 'Build and Push image using ACR Task'
  inputs:
    azureSubscription: 'ACR-myzomato'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az acr build \
        --registry myzomato \
        --image myimage:latest \
        --file .github/manifests/Dockerfile \
        .
