trigger:
- main

variables:
  # Docker / ACR
  dockerRegistryServiceConnection: '467aebc6-c2d7-48d1-af79-d79a67c80398'
  imageRepository: 'foodcart-node'
  containerRegistry: 'myacr'
  dockerfilePath: '.github/manifests/Dockerfile'
  tag: '$(Build.BuildId)'

  # AKS
  azureSubscriptionEndpoint: 'default'
  azureResourceGroup: 'Nayana'
  kubernetesCluster: 'managedevopsagent'
  namespace: 'prod'
  manifestsPath: '.github/manifests/deployment.yaml'

  # Service Principal for ACR login
  azureServicePrincipalId: '<YOUR-SP-APP-ID>'
  azureServicePrincipalKey: '<YOUR-SP-SECRET>'
  azureTenantId: '<YOUR-TENANT-ID>'

pool:
  name: magedpool

stages:
# ========== BUILD STAGE ==========
- stage: Build
  displayName: 'Build and Push Docker Image'
  jobs:
  - job: Build
    displayName: 'Build & Push Image'
    steps:
    - checkout: self

    - script: |
        echo "Listing repository files..."
        ls -R
      displayName: 'List Files in Repo'

    # Install Docker if not present
    - script: |
        if ! command -v docker &> /dev/null
        then
          echo "Installing Docker..."
          sudo apt-get update -y
          sudo apt-get install -y ca-certificates curl gnupg lsb-release apt-transport-https software-properties-common
          sudo mkdir -p /etc/apt/keyrings
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt-get update -y
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
          sudo usermod -aG docker $USER
          sudo systemctl start docker
          sudo systemctl enable docker
        fi
        docker version
      displayName: 'Install and Verify Docker'

    # Install Azure CLI if not present
    - script: |
        if ! command -v az &> /dev/null
        then
          echo "Installing Azure CLI..."
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
        fi
        az version
      displayName: 'Install and Verify Azure CLI'

    # Login to Azure and ACR using Service Principal
    - script: |
        echo "Ensuring Docker permissions..."
        sudo usermod -aG docker $USER
        sudo systemctl restart docker
        sleep 5

        echo "Logging into Azure using Service Principal..."
        az login --service-principal \
          -u $AZURE_SP_APP_ID \
          -p $AZURE_SP_PASSWORD \
          --tenant $AZURE_TENANT_ID

        echo "Logging into Azure Container Registry..."
        az acr login --name $(containerRegistry)
      env:
        AZURE_SP_APP_ID: $(azureServicePrincipalId)
        AZURE_SP_PASSWORD: $(azureServicePrincipalKey)
        AZURE_TENANT_ID: $(azureTenantId)
      displayName: 'Login to Azure and ACR'

    # Build Docker image
    - script: |
        echo "Building Docker image..."
        docker build -t $(containerRegistry).azurecr.io/$(imageRepository):$(tag) -f $(dockerfilePath) .
      displayName: 'Build Docker Image'

    # Push Docker image
    - script: |
        echo "Pushing Docker image to ACR..."
        docker push $(containerRegistry).azurecr.io/$(imageRepository):$(tag)
      displayName: 'Push Docker Image to ACR'

    # Update Kubernetes manifest
    - script: |
        echo "Updating Kubernetes manifest with new image tag..."
        sed -i "s|image: .*|image: $(containerRegistry).azurecr.io/$(imageRepository):$(tag)|" $(manifestsPath)
      displayName: 'Update Kubernetes Manifest'

    - publish: .github/manifests
      artifact: manifests

# ========== DEPLOY STAGE ==========
- stage: Deploy
  displayName: 'Deploy to AKS'
  dependsOn: Build
  jobs:
  - job: Deploy
    displayName: 'Deploy Application to AKS'
    steps:
    - download: current
      artifact: manifests

    - task: Kubernetes@1
      displayName: 'Deploy to AKS'
      inputs:
        connectionType: 'Azure Resource Manager'
        azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
        azureResourceGroup: $(azureResourceGroup)
        kubernetesCluster: $(kubernetesCluster)
        namespace: $(namespace)
        command: 'apply'
        useConfigurationFile: true
        configuration: '$(Pipeline.Workspace)/manifests/deployment.yaml'
